### ISSUE TITLE
Enable twitter cards preview 

### ISSUE THREAD

**Issue by michaelbzhu** [dormroomfund/blog#20]
Issue: currently, no previews show up when we make a tweet with a blog.dormroomfund.com link in it
- we have the correct meta tags in place in `Layout.js` and `[slug].js` but it still isn't rendering
- use https://cards-dev.twitter.com/validator to validate cards without posting dummy tweets

Looking at the heroku logs there appears to be an issue with the `useLocalStorage` hook in `utils`
```
2021-11-04T22:43:22.934265+00:00 app[web.1]: ReferenceError: window is not defined
2021-11-04T22:43:22.934273+00:00 app[web.1]:     at /app/.next/server/pages/post/[slug].js:1086:20
2021-11-04T22:43:22.934274+00:00 app[web.1]:     at Ha (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:26:317)
2021-11-04T22:43:22.934275+00:00 app[web.1]:     at Object.useState (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:28:301)
2021-11-04T22:43:22.934275+00:00 app[web.1]:     at exports.useState (/app/node_modules/react/cjs/react.production.min.js:23:281)
2021-11-04T22:43:22.934276+00:00 app[web.1]:     at useLocalStorage (/app/.next/server/pages/post/[slug].js:1083:42)
2021-11-04T22:43:22.934277+00:00 app[web.1]:     at Post (/app/.next/server/pages/post/[slug].js:1244:39)
2021-11-04T22:43:22.934277+00:00 app[web.1]:     at d (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
2021-11-04T22:43:22.934277+00:00 app[web.1]:     at bb (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
2021-11-04T22:43:22.934278+00:00 app[web.1]:     at a.b.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
2021-11-04T22:43:22.934279+00:00 app[web.1]:     at a.b.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
```

**Comment by michaelbzhu** [comment]
currently when I try to access the site as the TwitterBot i get the following output; which does not contain the twitter meta tags even though they exist when you view them through the browser

`curl -v -A Twitterbot https://blog.dormroomfund.com/post/trying-to-find-more-meaning-in-2020-she-moved-to-london`

```
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <link
    rel="preload"
    href="/_next/static/css/0962f4c77eadecb06815.css"
    as="style"
  />
  <link
    rel="stylesheet"
    href="/_next/static/css/0962f4c77eadecb06815.css"
    data-n-g=""
  />
  <link
    rel="preload"
    href="/_next/static/css/e67461cc4739eed29d6f.css"
    as="style"
  />
  <link
    rel="stylesheet"
    href="/_next/static/css/e67461cc4739eed29d6f.css"
    data-n-p=""
  />
  <noscript data-n-css="true"></noscript>
  <link
    rel="preload"
    href="/_next/static/chunks/main-d283b4ab393ebd284c3e.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/webpack-e067438c4cf4ef2ef178.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/framework.9707fddd9ae5927c17c3.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/commons.e3c12cb767780eaa6561.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/pages/_app-2aede0dff733f07d9c43.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/b0502715578cc2fbb7f951510c934bca5c15ecdd.a7ff8789401143be1ac4.js"
    as="script"
  />
  <link
    rel="preload"
    href="/_next/static/chunks/pages/post/%5Bslug%5D-1d78a1ea4dd302bb73c6.js"
    as="script"
  />
</head>

```

**Comment by michaelbzhu** [comment]
useful community debug post: https://twittercommunity.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736

I believe the issue is that the blog is server side rendered, meaning that the website is generated each time a user makes a request to blog.dormroomfund.com
- the benefit of this is that the blog website doesn't need to be redeployed everytime there is a new blog post
- the problem is that the TwitterBot can't access the meta tags since the tags are not static
If we were to switch to prerendering this would allow twitter cards to show but would force us to rebuild the website every time we create a new blog post

**Comment by petercrackthecode** [comment]
Good update. I'll ponder on how we rebuild the website to static without messing things up too much.

**Comment by michaelbzhu** [comment]
Currently looking into [Incremental Static Regeneration](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration) and what would be the most optimal redeployment pattern for new/updated blog posts
